{{- if .Values.jaegerEnabled -}}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaegertracing-all-in-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaegertracing-all-in-one
  template:
    metadata:
      labels:
        app: jaegertracing-all-in-one
    spec:
      containers:
        - name: jaeger-all-in-one
          image: jaegertracing/all-in-one:1.38
          ports:
            - containerPort: 5775
              protocol: UDP
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
            - containerPort: 5778
              protocol: TCP
            - containerPort: 16686
              protocol: TCP
            - containerPort: 14268
              protocol: TCP
            - containerPort: 9411
              protocol: TCP
            - containerPort: 14250

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-service
  labels:
    app: jaegertracing-all-in-one
spec:
  type: NodePort
  selector:
    app: jaegertracing-all-in-one
  ports:
    - port: 16686
      targetPort: 16686
      nodePort: 30015
      name: jaegerservice
    - port: 14250
      targetPort: 14250
      name: jaegerservice-rpc


{{- end }}
